### ISSUE TITLE
Deletion of most msg definitions

### ISSUE THREAD

**Issue by StefanFabian** [ctu-mrs/mrs_msgs#7]
Hey,
I've just noticed that your recent commit d95e5fbd2b0173a7c789919c1ee524b74ee5dabd deleted most of the msgs defined in this repository.
Unfortunately, that makes `ouster_ros` not compile for us anymore since it uses your OusterInfo message for some reason.
Was this intended?

**Comment by matemat13** [comment]
@klaxalk was that intentional? Maybe we should move the `OusterInfo` message to the Ouster driver?

**Comment by klaxalk** [comment]
@matemat13 Ye, I would move sensor-related messages to the sensor drivers.

@StefanFabian Most of the non-core messages were moved to https://github.com/ctu-mrs/mrs_modules_msgs, which are now part of the https://github.com/ctu-mrs/mrs_uav_modules. Please follow this [document](https://docs.google.com/document/d/1NibHqNdyzzAYE7DNIMMq1HmzyFrBnISbzV17dP-waYw/edit?usp=sharing) to upgrade to the new system. If you want to stay in the old system, the repositories **uav_core**, **uav_modules**, and **simulation** should be mutually compatible (with their submodules) in the last state of the old system.
